test_name: test_validate_configs
test_filename: test_cli.py
docstring:
  Tests configuration validation by adding a semantic model file with errors.
expectation_description:
  There should be two validation failures with `bad_semantic_model`.
---
(To see warnings and future-errors, run again with flag `--show-all`)
â€¢ [91m[1mERROR[0m: with semantic model `bad_semantic_model`  - Failed to query dimensions in data warehouse for semantic model `bad_semantic_model`
Received following error from data warehouse:
Runtime Error
  Binder Error: Referenced column "non_existent_column" not found in FROM clause!
  Candidate bindings: "bad_semantic_model_src_0.transaction_amount_usd", "bad_semantic_model_src_0.transaction_type_name", "bad_semantic_model_src_0.id_transaction", "bad_semantic_model_src_0.ds", "bad_semantic_model_src_0.id_customer"
  LINE 28:   , non_existent_column AS bad_dimension
               ^
â€¢ [91m[1mERROR[0m: with dimension `bad_dimension` in semantic model `bad_semantic_model`  - Unable to query dimension `bad_dimension` on semantic model `bad_semantic_model` in data warehouse
Received following error from data warehouse:
Runtime Error
  Binder Error: Referenced column "non_existent_column" not found in FROM clause!
  Candidate bindings: "bad_semantic_model_src_0.transaction_amount_usd", "bad_semantic_model_src_0.transaction_type_name", "bad_semantic_model_src_0.id_transaction", "bad_semantic_model_src_0.ds", "bad_semantic_model_src_0.id_customer"
  LINE 4:   non_existent_column AS bad_dimension
            ^
